spring.application.name=HotelReservationSystem
spring.datasource.url=jdbc:mysql://localhost:3306/HotelDatabase?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
Room.Type.STANDARD.Price=700
Room.Type.DELUXE.Price=1200
Room.Type.SUITE.Price=3000
